import { NextPage } from 'next';
import Head from 'next/head';
import { AdminPanel, Header, Footer } from '@atomic';

import styles from '../styles/Home.module.scss';
import { footerData, navItems } from 'utils/data';
import { ICollection, IEvent, IMuseum, IUser } from 'types';

interface IAdminPageProps {
  museums: IMuseum[];
  events: IEvent[];
  collections: ICollection[];
  users: IUser[];
}

const AdminPage: NextPage<IAdminPageProps> = ({
  museums,
  events,
  collections,
  users,
}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>National Museums Scotland - Home Page</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Header navItems={navItems} />
      <AdminPanel
        museums={museums}
        events={events}
        collections={collections}
      />
      <Footer {...footerData} />
    </div>
  );
};

export const getServerSideProps = async (context: any) => {
  const token = context.req.cookies.token;

  const fetchMuseums = await fetch('http://localhost:3000/api/v1/museums');
  const fetchEvents = await fetch('http://localhost:3000/api/v1/events');
  const fetchCollections = await fetch(
    'http://localhost:3000/api/v1/collections',
  );
  const fetchUsers = await fetch('http://localhost:3000/api/v1/users', {
    headers: { Authorization: `Bearer ${token}` },
  });

  const museums = await fetchMuseums.json();
  const events = await fetchEvents.json();
  const collections = await fetchCollections.json();
  const users = await fetchUsers.json();

  return {
    props: {
      museums: museums.data.museums,
      events: events.data.events,
      collections: collections.data.collections,
      users: users,
    },
  };
};
export default AdminPage;
