import Head from 'next/head';
import {
  Header,
  Hero,
  OurWork,
  FeaturedSection,
  CTABanner,
  GridSection,
  Footer,
} from '@atomic';
import {
  navItems,
  heroData,
  ourWorkData,
  featuredEventsData,
  museumsData,
  footerData,
  CTABannerProps,
} from '../utils/data';

import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>National Museums Scotland - Home Page</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Header navItems={navItems} />
      <Hero {...heroData} />
      <OurWork {...ourWorkData} />
      <FeaturedSection {...featuredEventsData} />
      <CTABanner {...CTABannerProps} />
      <GridSection content={museumsData} />
      <Footer {...footerData} />
    </div>
  );
}
