import { NextPage } from 'next';
import Head from 'next/head';
import {
  Header,
  Hero,
  OurWork,
  FeaturedSection,
  CTABanner,
  GridSection,
  Footer,
} from '@atomic';
import { navItems, heroData, footerData, CTABannerProps } from '../utils/data';

import styles from '../styles/Home.module.scss';

import { IEvent, IMuseum } from '../types';
interface IHomeProps {
  events: IEvent[];
  museums: IMuseum[];
}

const Home: NextPage<IHomeProps> = ({ events = [], museums }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>National Museums Scotland - Home Page</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Header navItems={navItems} />
      <Hero {...heroData} />
      <OurWork
        title='What We Offer at National Museums Scotland'
        blocks={[
          {
            icon: 'collections.svg',
            iconAlt: 'book icon',
            title: 'Curating Collections',
            description:
              "At National Museums Scotland, we take pride in curating a diverse and extensive collection of artefacts that showcase Scotland's rich cultural and historical heritage. Our team of experts works tirelessly to acquire, preserve, and interpret these collections, ensuring that they remain accessible for generations to come.",
          },
          {
            icon: 'events.svg',
            iconAlt: 'calender icon',
            title: 'Curating Collections',
            description:
              "At National Museums Scotland, we take pride in curating a diverse and extensive collection of artefacts that showcase Scotland's rich cultural and historical heritage. Our team of experts works tirelessly to acquire, preserve, and interpret these collections, ensuring that they remain accessible for generations to come.",
          },
          {
            icon: 'history.svg',
            iconAlt: 'scroll icon',

            title: 'Curating Collections',
            description:
              "At National Museums Scotland, we take pride in curating a diverse and extensive collection of artefacts that showcase Scotland's rich cultural and historical heritage. Our team of experts works tirelessly to acquire, preserve, and interpret these collections, ensuring that they remain accessible for generations to come.",
          },
        ]}
      />
      <FeaturedSection events={events} />
      <CTABanner {...CTABannerProps} />
      <GridSection museums={museums} />
      <Footer {...footerData} />
    </div>
  );
};

export const getServerSideProps = async () => {
  const fetchEvents = await fetch('http://localhost:3000/api/v1/events');
  const fetchMuseums = await fetch('http://localhost:3000/api/v1/museums');
  const events = await fetchEvents.json();
  const museums = await fetchMuseums.json();

  return {
    props: {
      events: events.data.events,
      museums: museums.data.museums,
    },
  };
};

export default Home;
