import Head from 'next/head';
import styles from '../styles/Home.module.scss';

import Button from '../Atomic/Atoms/Button/Button';
import Nav from '../Atomic/Molecules/Nav/Nav';

export default function Home() {
  const items = [
    { page: 'Home', href: 'www.google.com' },
    { page: 'Museums', href: 'www.google.com' },
    { page: 'Collections', href: 'www.google.com' },
    { page: 'Login', href: 'www.google.com' },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>National Museums Scotland - Home Page</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <Nav items={items} />
      <Button
        href='www.google.com'
        varient='cta'
      >
        View Our Events
      </Button>
    </div>
  );
}
